sequenceDiagram
    actor user
    participant agent
    
    note over user,agent: 最终操作（清理、实装，等等）
    user <<->> agent: 沟通需要执行哪些操作
    opt 这些需要询问用户的意见
        agent ->> agent: 清理除了TransPlayVault下，整个流程中其他地方涉及到的现在已经无用的目录。（提醒用户已经备份到origin下了）。
        agent ->> agent: 直接把translated覆盖到游戏mod或创意工坊（询问user意见来决定）来使用。
    end